version: '3'

services:
  janus:
    build:
      context: .
      dockerfile: ./janus/Dockerfile
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes: 
      - ./janus/config:/opt/janus/etc/janus
      - ./janus/recordings:/opt/janus/share/janus/recordings
    ports:
      - "8088:8088"
      - "8088:8088/udp"
      - "8089:8089"
      - "8089:8089/udp"
      - "8188:8188"
      - "8188:8188/udp"
